  # This is a basic workflow that is manually triggered

name: Employee

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

       # Compile your classes
      - name: Compile classes
        working-directory: ./src
        run: javac -cp javac -cp "../junit-jupiter-api-5.6.0.jar" employeeclass/MainClass.java employeeclass/Employee.java employeeclass/MainClass.java employeeclass/Employee.java

      # Compile your tests
      - name: Compile tests
        working-directory: ./test
        run: javac -cp "../junit-jupiter-api-5.6.0.jar:../src:." test/employeeclass/EmployeeTest.java
        
      # Run your tests
      - name: Run tests
        working-directory: ./test
        run: java -cp "../junit-jupiter-api-5.6.0.jar" -jar "../testresources/junit-jupiter-api-5.6.0.jar" --select-class employee.EmployeeTest
